fx_version ('cerulean')
game ('gta5')

lua54 ('yes')

description 'FiveM script template with client, server, and web UI components.'
version '1.0.0'
author 'NoCap'


client_scripts ({
    'client/*.lua'
})

server_scripts ({
    'server/*.lua'
})

ui_page ({'web/index.html'})

files ({
    'web/**'
})




-- Script generated by VSCode FiveM Builder
